### ISSUE TITLE
`require` within function

### ISSUE THREAD

**Issue by karlhorky** [kunstloch/sentiment-analysis#2]
There is a `require` within the main function on the page (line `22`), which will cause the `https` module to be "required" (re-imported) every time the `sentimentAnalisys` function is called (it is called every time the user answers "yes").

https://github.com/kunstloch/sentiment-analysis/blob/beccde8fb39377cbd966b5cb31ff818d9e2375c8/index.js#L13-L22

Best practice is to try to have all `import`s and `require`s at the top of the file.

**Comment by kunstloch** [comment]
changed order
