### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by karlhorky** [kunstloch/sentiment-analysis#4]
Some variables in the code are not currently used.

![Screen Shot 2019-10-01 at 16 35 35](https://user-images.githubusercontent.com/1935696/65975971-bcb51e80-e46f-11e9-9480-b16eb605cef5.png)

![Screen Shot 2019-10-01 at 17 09 50](https://user-images.githubusercontent.com/1935696/65975976-bf177880-e46f-11e9-974b-f56be00d0a8a.png)

They are recognizable because their colors are a bit dimmer than the normal variables.

**Comment by kunstloch** [comment]
changed

**Comment by karlhorky** [comment]
Thanks @kunstloch ! I assume it was in this commit here? https://github.com/kunstloch/sentiment-analysis/commit/9d81b9365c70834808fa53b409b3dd1acf2ea71c

It's best practice to say in which commit / pull request a feature was implemented or bug was fixed. You can do this by either:

1. Copy the full URL to the commit - the format should be like this:
   
   `https://github.com/<name>/<repo>/commit/<commit hash>`

2. Copy only the commit hash part of the URL (from the format above)

3. **Hacker mode:** Close the issue from the commit / pull request message! You can do this by writing `Closes #<issue number>` in the pull request description or   in the "body" of the commit message (after a blank line following the title line). 

   More information here: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
